### ISSUE TITLE
Not able to ssh to a Salt master machine

### ISSUE THREAD

**Issue by EslamElHusseiny** [warpdotdev/Warp#4075]
### Describe the bug

SSH to a salt master machine fails with the following error 
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'Interpreter' object has no attribute 'do_export'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hulu/bin/saltshell.py", line 400, in <module>
    interpreter.onecmd(" ".join(sys.argv[2:]))
  File "/usr/lib/python3.6/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/opt/hulu/bin/saltshell.py", line 231, in default
    print('{}: command not found'.format(line))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc9c' in position 237: surrogates not allowed
debug1: client_input_channel_req: channel 1 rtype exit-status reply 0
debug1: client_input_channel_req: channel 1 rtype eow@openssh.com reply 0
debug1: channel 1: free: client-session, nchannels 2
debug1: channel 0: free: /Users/eslam.elhusseiny/.ssh/17054113946846, nchannels 1
Connection to supermaster.staging.hulu.com closed.
Transferred: sent 7132, received 3852 bytes, in 6.4 seconds
Bytes per second: sent 1123.1, received 606.6
debug1: Exit status 1
```

### To reproduce

SSH to a salt master machine (Shell is different) 

### Expected behavior

Being able to ssh to salt master machine

### Operating system

MacOS

### Operating system and version

14.2.1 (23C71)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.01.09.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @EslamElHusseiny Thanks for letting us know. If the remote shell is something other than bash/zsh/fish, Warps SSH wrapper won't work as intended and I recommend you disable it in Settings > Features > Session > SSH Wrapper. This will disable Warp features, but the remote SSH connection should work as normal.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.
