### ISSUE TITLE
ubuntu warp-terminal unable to launch

### ISSUE THREAD

**Issue by cadnav** [warpdotdev/Warp#4310]
### Describe the bug

(miniconda3) ubuntu@siclarity-gts:~/Downloads$ warp-terminal --help
stdout is a tty true, in CI false.  using logfile: false
10:11:49 [INFO] Encountered unknown command-line arguments: ["--help"]
10:11:49 [INFO] Spawning terminal server process...
10:11:49 [INFO] Running terminal server...
thread 'background-executor-29' panicked at app/src/user_config/native.rs:60:18:
Should be able to create watcher: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }), paths: [] }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
10:11:49 [WARN] Failed to load font Some("/usr/share/fonts/X11/Type1/c0419bt_.pfb"): InvalidFontFormat("Type 1")
10:11:49 [WARN] Failed to load font Some("/usr/share/fonts/type1/gsfonts/b018012l.pfb"): InvalidFontFormat("Type 1")
10:11:49 [WARN] Failed to load font Some("/usr/share/fonts/type1/gsfonts/s050000l.pfb"): InvalidFontFormat("Type 1")
10:11:49 [WARN] Unable to fetch system color scheme: MethodError(
    OwnedErrorName(
        ErrorName(
            Str(
                Owned(
                    "org.freedesktop.portal.Error.NotFound",
                ),
            ),
        ),
    ),
    Some(
        "Requested setting not found",
    ),
    Msg {
        type: Error,
        sender: UniqueName(
            Str(
                Borrowed(
                    ":1.54",
                ),
            ),
        ),
        reply-serial: 2,
        body: Signature(
            "s",
        ),
    },
)
10:11:49 [WARN] Failed to load font: Hack due to error Font family Hack does not contain any valid fonts

### To reproduce

install deb package from warp terminal website 
run `sudo dpkg -i <deb package>`
warp-terminal 

### Operating system

Linux

### Operating system and version

ubuntu 20/22

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by LFd3v** [comment]
> thread 'background-executor-29' panicked at app/src/user_config/native.rs:60:18:
> Should be able to create watcher: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }), paths: [] }

Hi, there. Could you please provide more info, like what version of Ubuntu that is being used?

It seems that the error was related to a limit of the maximum number of opened files, if this is the case, this may help you troubleshoot/fix the issue:

https://www.howtogeek.com/805629/too-many-open-files-linux/

**Comment by LFd3v** [comment]
> 16:16:35 [INFO] Cpu: llvmpipe (LLVM 15.0.7, 128 bits)
> 16:16:35 [INFO] 	Driver: llvmpipe (Mesa 23.2.1-1ubuntu3.1~22.04.2 (LLVM 15.0.7))
> 16:16:35 [INFO] Cpu: llvmpipe (LLVM 15.0.7, 128 bits)
> 16:16:35 [INFO] 	Driver: Unknown

It seems that your problem is different from the one shown in OP, there is no GPU hardware available. Are you trying to run the app in a virtual machine by any chance? If not, you may need to verify that the proper GPU drivers are installed, and preferably also make sure Vulkan libraries are installed for you GPU, if it supports it.

**Comment by g4nd4lf** [comment]
thanks! I guess that is beyond my current knowledge of Linux in general and Ubuntu in particular. I just installed Ubuntu in an old Imac 11,1 in order to give the machine a second oportunity. This imac use an old GPU Ati Mobility Radeon HD 4850 but I don't know how to install the proper drivers. Do you know where should I study to learn more about this? Thank you anyway for the help!!

**Comment by LFd3v** [comment]
@g4nd4lf I think this model works with the `radeon` driver, which does not support Vulkan, but them Warp should work with its OpenGL driver as far as I know. There were reports that previous versions had problems with machines using `radeon`, but hopefully it is fixed now. One tip: I have a similar machine, and in the past I had to blacklist the Intel GPU driver (`i915`) in order for some apps to work correctly, you may also need to manually set the proper driver, this may help as well (it is for Arch, but the same info applies to Ubuntu, for instance):
https://wiki.archlinux.org/title/Hardware_video_acceleration

**Comment by alokedesai** [comment]
@g4nd4lf The latest version of Warp should have a fix for the issue you're experiencing. Could you try on the latest version of Warp to confirm?

**Comment by g4nd4lf** [comment]
Yes! Great! I just checked latest version (2024.03.12.08.02.stable ) and it works like a charm with no need of other change of preferences or configurations. A few days ago I was able to run a previous version of warp-terminal using "env WGPU_BACKEND=gl warp-terminal" in the terminal. But now it is not needed.
Thank you all!
regards and congratulations for this great terminal, I love it!

**Comment by g4nd4lf** [comment]
Yes! Great! I just checked latest version (2024.03.12.08.02.stable ) and it
works like a charm with no need of other change of preferences or
configurations. A few days ago I was able to run a previous version of
warp-terminal using "env WGPU_BACKEND=gl warp-terminal" in the terminal.
But now it is not needed.
Thank you all!
regards and congratulations for this great terminal, I love it!
