### ISSUE TITLE
[Linux] Warp panics on startup

### ISSUE THREAD

**Issue by oliveirarleo** [warpdotdev/Warp#4840]
### Describe the bug

After updating to newest warp version, the app simply did not start, here is the error message when I run via zsh:
```
RUST_BACKTRACE=full warp-terminal
/nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/nwsbnbj4xgfq2x45df9xg2b77953h2zz-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp)
15:19:23 [INFO] Spawning terminal server process...
15:19:23 [INFO] Running app with windowing system: Wayland
thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:164:14:
should be able to create event loop: Os(OsError { line: 80, file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })
stack backtrace:
   0:     0x560a7d20205b - <unknown>
   1:     0x560a7c954d00 - <unknown>
   2:     0x560a7d1fd5e3 - <unknown>
   3:     0x560a7d201df4 - <unknown>
   4:     0x560a7d204370 - <unknown>
   5:     0x560a7d20408f - <unknown>
   6:     0x560a7d20488e - <unknown>
   7:     0x560a7d204792 - <unknown>
   8:     0x560a7d202556 - <unknown>
   9:     0x560a7d204500 - <unknown>
  10:     0x560a7c60b265 - <unknown>
  11:     0x560a7c60b7b3 - <unknown>
  12:     0x560a7df885a9 - <unknown>
  13:     0x560a7e22769c - <unknown>
  14:     0x560a7e226c93 - <unknown>
  15:     0x560a7d1d5143 - <unknown>
  16:     0x560a7d1d515d - <unknown>
  17:     0x560a7d1f3da5 - <unknown>
  18:     0x560a7d1d56cc - <unknown>
/nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/nwsbnbj4xgfq2x45df9xg2b77953h2zz-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp)
  19:     0x7f9b4a70d10e - __libc_start_call_main
  20:     0x7f9b4a70d1c9 - __libc_start_main@@GLIBC_2.34
  21:     0x560a7c752b8e - <unknown>
  22:                0x0 - <unknown>
15:19:23 [INFO] Received empty message; assuming the connection has been closed.
```

### To reproduce

1. Updated to version 0.2024.04.16.08.02.stable_00
2. Try to open the terminal either via the icon, or terminal
3. App simply does not open

### Expected behavior

1. Updated to version 0.2024.04.16.08.02.stable_00
2. Try to open the terminal either via the icon, or terminal
3. App opens

### Operating system

Linux

### Operating system and version

Nixos 23.11

### Current Warp version

0.2024.04.16.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

0.2024.04.2

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Mastermindaxe** [comment]
I've got the same issue. Also running NixOS. Installing `warp-terminal` via `nix-shell -p warp-terminal` and then using it works fine. Maybe a NixOS bug? I haven't found any other bug reports in the nixpkgs repo though.

**Comment by alokedesai** [comment]
Hi @oliveirarleo, sorry for the issues here. We believe we fixed this with the latest Warp update last week. Could you try again with the latest version (`v0.2024.04.23.08.01.stable_03`)? You can download it at https://www.warp.dev/ if needed.

**Comment by alokedesai** [comment]
> I've got the same issue. Also running NixOS. Installing `warp-terminal` via `nix-shell -p warp-terminal` and then using it works fine. Maybe a NixOS bug? I haven't found any other bug reports in the nixpkgs repo though.

@Mastermindaxe What version of Warp are you on? Could you share your warp logs when the panic occurs?

**Comment by Mastermindaxe** [comment]
It's still an old version, but here's the log output:
```
❯ warp-terminal
/nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/nwsbnbj4xgfq2x45df9xg2b77953h2zz-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp)
22:39:32 [INFO] Spawning terminal server process...
22:39:32 [INFO] Running app with windowing system: Wayland
thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:164:14:
should be able to create event loop: Os(OsError { line: 80, file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
22:39:32 [INFO] Received empty message; assuming the connection has been closed.
```
I'll see if an update fixes it. It should tbh

**Comment by alokedesai** [comment]
@Mastermindaxe Yeah, I'm fairly positive this should be fixed in the latest version of Warp :) Will close this out upon confirmation though.

**Comment by alokedesai** [comment]
Great, I'm going to close this out as I'm very sure this should now be fixed :)

**Comment by oliveirarleo** [comment]
Thanks for closing the ticket for me. It works indeed!
